### ISSUE TITLE
Custom build can't find metadata

### ISSUE THREAD

**Issue by ItsJamie9494** [vicr123/theInstaller#1]
I am trying to use theInstaller to make my own installer for thePhoto.

Here is what happens on run:

![image](https://user-images.githubusercontent.com/22264706/49412124-30877d00-f720-11e8-8b45-a18b7b205032.png)

The metadata (installer.pro) is set to this: 
DEFINES += INSTALLER_METADATA_URL=\\\"http://awesometech10.github.io/theInstaller/thephoto/installer.json\\\"

That website is a live metadata site. Why does the installer not find it?

**Comment by vicr123** [comment]
Should be three slashes behind the first quote: `_URL=\\\"http`

**Comment by ItsJamie9494** [comment]
There is three slashes.
![image](https://user-images.githubusercontent.com/22264706/49419657-9aae1b00-f73c-11e8-95c9-32c44279446e.png)
For some reason, GitHub got rid of two of the slashes
